# Generated by Django 4.2.4 on 2023-08-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='picture')),
                ('cate', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('auther', models.CharField(max_length=50)),
            ],
        ),
    ]
