# Generated by Django 4.2.4 on 2023-08-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interior',
            new_name='interiors',
        ),
    ]
