# Generated by Django 4.2.4 on 2023-08-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_interior_interiors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interiors',
            old_name='auther',
            new_name='author',
        ),
    ]
