# Generated by Django 4.2.4 on 2023-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_auther_interiors_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='interiors2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='picture')),
                ('desc', models.TextField()),
                ('date', models.DateField(max_length=50)),
            ],
        ),
    ]
