# Generated by Django 4.2.4 on 2023-08-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_interiors_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='interiors2',
        ),
    ]
