# Generated by Django 4.2.4 on 2023-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_interiors_interior_delete_interiors2'),
    ]

    operations = [
        migrations.CreateModel(
            name='interior1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='picture')),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
