# Generated by Django 4.2.4 on 2023-08-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_interior1_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior1',
            name='img',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
