# Generated by Django 4.2.4 on 2023-08-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_interior1_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='interior2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
